

// This is automatically generated by the Sage script
// 'create_tetsts_matrices.sage'

SNmatrix<double,2> testMatrix_FOO_A()
{
    SNmatrix<double,2> S(0);

    S.at(0,0)=1.00000000000000;
S.at(0,1)=2.00000000000000;
S.at(1,0)=3.00000000000000;
S.at(1,1)=4.00000000000000;

    return S;
}

SNmatrix<double,2> testMatrix_FOO_A_P()
{
    SNmatrix<double,2> S(0);

    S.at(0,1)=1.00000000000000;
S.at(1,0)=1.00000000000000;

    return S;
}

SNlowerTriangular<double,2> testMatrix_FOO_A_L()
{
    SNlowerTriangular<double,2> S(0);

    S.at(0,0)=1.00000000000000;
S.at(1,0)=0.333333333333333;
S.at(1,1)=1.00000000000000;

    return S;
}

SNupperTriangular<double,2> testMatrix_FOO_A_U()
{
    SNupperTriangular<double,2> S(0);

    S.at(0,0)=3.00000000000000;
S.at(0,1)=4.00000000000000;
S.at(1,1)=0.666666666666667;

    return S;

}

AutoTestMatrix<double,2> atm_FOO( testMatrix_FOO_A(),testMatrix_FOO_A_P(),testMatrix_FOO_A_L(),testMatrix_FOO_A_U()  );


// This is automatically generated by the Sage script
// 'create_tetsts_matrices.sage'

SNmatrix<double,3> testMatrix_BAR_A()
{
    SNmatrix<double,3> S(0);

    S.at(0,0)=1.00000000000000;
S.at(0,1)=2.00000000000000;
S.at(0,2)=6.20000000000000;
S.at(1,0)=-3.00000000000000;
S.at(1,1)=2.50000000000000;
S.at(1,2)=4.00000000000000;
S.at(2,0)=0.330000000000000;
S.at(2,1)=0.666000000000000;
S.at(2,2)=1.33333000000000;

    return S;
}

SNmatrix<double,3> testMatrix_BAR_A_P()
{
    SNmatrix<double,3> S(0);

    S.at(0,1)=1.00000000000000;
S.at(1,0)=1.00000000000000;
S.at(2,2)=1.00000000000000;

    return S;
}

SNlowerTriangular<double,3> testMatrix_BAR_A_L()
{
    SNlowerTriangular<double,3> S(0);

    S.at(0,0)=1.00000000000000;
S.at(1,0)=-0.333333333333333;
S.at(1,1)=1.00000000000000;
S.at(2,0)=-0.110000000000000;
S.at(2,1)=0.332117647058824;
S.at(2,2)=1.00000000000000;

    return S;
}

SNupperTriangular<double,3> testMatrix_BAR_A_U()
{
    SNupperTriangular<double,3> S(0);

    S.at(0,0)=-3.00000000000000;
S.at(0,1)=2.50000000000000;
S.at(0,2)=4.00000000000000;
S.at(1,1)=2.83333333333333;
S.at(1,2)=7.53333333333333;
S.at(2,2)=-0.728622941176471;

    return S;

}

AutoTestMatrix<double,3> atm_BAR( testMatrix_BAR_A(),testMatrix_BAR_A_P(),testMatrix_BAR_A_L(),testMatrix_BAR_A_U()  );


// This is automatically generated by the Sage script
// 'create_tetsts_matrices.sage'

SNmatrix<double,3> testMatrix_ooIJXAooDhmylq_A()
{
    SNmatrix<double,3> S(0);

    S.at(0,0)=-1.00000000000000;
S.at(0,1)=2.00000000000000;
S.at(0,2)=-6.20000000000000;
S.at(1,0)=3.00000000000000;
S.at(1,1)=2.50000000000000;
S.at(1,2)=-4.00000000000000;
S.at(2,0)=0.333333333333333;
S.at(2,1)=0.666666666666667;
S.at(2,2)=1.33333333333333;

    return S;
}

SNmatrix<double,3> testMatrix_ooIJXAooDhmylq_A_P()
{
    SNmatrix<double,3> S(0);

    S.at(0,1)=1.00000000000000;
S.at(1,0)=1.00000000000000;
S.at(2,2)=1.00000000000000;

    return S;
}

SNlowerTriangular<double,3> testMatrix_ooIJXAooDhmylq_A_L()
{
    SNlowerTriangular<double,3> S(0);

    S.at(0,0)=1.00000000000000;
S.at(1,0)=-0.333333333333333;
S.at(1,1)=1.00000000000000;
S.at(2,0)=0.111111111111111;
S.at(2,1)=0.137254901960784;
S.at(2,2)=1.00000000000000;

    return S;
}

SNupperTriangular<double,3> testMatrix_ooIJXAooDhmylq_A_U()
{
    SNupperTriangular<double,3> S(0);

    S.at(0,0)=3.00000000000000;
S.at(0,1)=2.50000000000000;
S.at(0,2)=-4.00000000000000;
S.at(1,1)=2.83333333333333;
S.at(1,2)=-7.53333333333333;
S.at(2,2)=2.81176470588235;

    return S;

}

AutoTestMatrix<double,3> atm_ooIJXAooDhmylq( testMatrix_ooIJXAooDhmylq_A(),testMatrix_ooIJXAooDhmylq_A_P(),testMatrix_ooIJXAooDhmylq_A_L(),testMatrix_ooIJXAooDhmylq_A_U()  );


// This is automatically generated by the Sage script
// 'create_tetsts_matrices.sage'

SNmatrix<double,3> testMatrix_ooTBBRooWpZkfJ_A()
{
    SNmatrix<double,3> S(0);

    S.at(0,0)=1.00000000000000;
S.at(0,1)=2.00000000000000;
S.at(0,2)=3.00000000000000;
S.at(1,0)=2.00000000000000;
S.at(1,1)=5.00000000000000;
S.at(2,0)=3.00000000000000;
S.at(2,1)=8.00000000000000;

    return S;
}

SNmatrix<double,3> testMatrix_ooTBBRooWpZkfJ_A_P()
{
    SNmatrix<double,3> S(0);

    S.at(0,1)=1.00000000000000;
S.at(1,2)=1.00000000000000;
S.at(2,0)=1.00000000000000;

    return S;
}

SNlowerTriangular<double,3> testMatrix_ooTBBRooWpZkfJ_A_L()
{
    SNlowerTriangular<double,3> S(0);

    S.at(0,0)=1.00000000000000;
S.at(1,0)=0.333333333333333;
S.at(1,1)=1.00000000000000;
S.at(2,0)=0.666666666666667;
S.at(2,1)=0.500000000000000;
S.at(2,2)=1.00000000000000;

    return S;
}

SNupperTriangular<double,3> testMatrix_ooTBBRooWpZkfJ_A_U()
{
    SNupperTriangular<double,3> S(0);

    S.at(0,0)=3.00000000000000;
S.at(0,1)=8.00000000000000;
S.at(1,1)=-0.666666666666667;
S.at(1,2)=3.00000000000000;
S.at(2,2)=-1.50000000000000;

    return S;

}

AutoTestMatrix<double,3> atm_ooTBBRooWpZkfJ( testMatrix_ooTBBRooWpZkfJ_A(),testMatrix_ooTBBRooWpZkfJ_A_P(),testMatrix_ooTBBRooWpZkfJ_A_L(),testMatrix_ooTBBRooWpZkfJ_A_U()  );
