// This file is automatically generated by
// tests_fd_ ooTQFOooJrAfLb.sage
//

SNmatrix<TYPE,SIZE> testsMatrix_ooTQFOooJrAfLb_A()
{
    SNmatrix<TYPE,SIZE> S(0);

    POPULATE_A

    return S;
}

SNupperTriangularMatrix<TYPE,SIZE> testsMatrix_ooTQFOooJrAfLb_U()
{
    SNupperTriangularMatrix<TYPE,SIZE> S(0);

    POPULATE_U

    return S;
}
